/**
 * IBM DevOps Metrics API
 * This is an API to gather data about significant events in the software delivery lifecycle
 *
 * OpenAPI spec version: 1.0.0
 * Contact: acm@us.ibm.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class InlineResponse400 (
  message: Option[String] = None
) extends ApiModel


